package:
  name: python-fmask
  version: "0.2.1"

source:
  fn: python-fmask-0.2.1.zip
  url: https://bitbucket.org/chchrsc/python-fmask/downloads/python-fmask-0.2.1.zip
  md5: c439f5f4eb11b8496fe5331eeaa5590c
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - six = six:main
    #
    # Would create an entry point called six that calls six.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
 number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - scipy
    - gdal
    - rios

test:
  # Python imports
  imports:
    - fmask

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/chchrsc/python-fmask/
  license: GPL
  summary: 'Python implementation of the FMask cloud and shadow masking algorithm for satellite imagery'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
