package:
  name: rios
  version: "1.4.2"

source:
  fn: rios-1.4.2.zip
  url: https://bitbucket.org/chchrsc/rios/downloads/rios-1.4.2.zip
  md5: 689d2eeac2957b396932719ee94825f6
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - six = six:main
    #
    # Would create an entry point called six that calls six.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - gdal
    - krb5

test:
  # Python imports
  imports:
    - rios

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/chchrsc/rios/
  license: GPL
  summary: 'Raster Input/Output Simplification'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
